### PR TITLE
switch pm3 client submodule to rrg repo

### PR DESCRIPTION
**Pull request by ca1e**
update pm3 client verion.
once I build success and installed on my phone,it still an old version pm3 client in the termux view and I dont know why.

### CODE REVIEW

**Comment by ca1e** [comment]
I just comment the eMRTD codes https://github.com/RfidResearchGroup/proxmark3/blob/c13ad9dcc66acf01d2ae7a1f0b8bfb5f9715f1b3/client/src/cmdhf.c#L397  to avoid build err and it works fine

**Comment by doegox** [comment]
ha ok, hmm it would be better to see why the build fails with emrtd and fix it. Can you share more info ?

**Comment by ca1e** [comment]
haha of cource ok. sorry just aim to proof the new version before. It just appeared yesterday and I cannt repruduce right now.may be the repo fixed it? I am really not good at it(android NDK).I just need a new version pm3 client on my android phone.

**Comment by doegox** [comment]
ok, anyway I'll let @xianglin1998 decide if this PR is ok for his repo.

**Comment by xianglin1998** [comment]
Yes, we can use rrg repo, that is latest.
If your want to use termux view:
 1. You must to crocess compile pm3 client 
 2. [Update into file](https://github.com/RfidResearchGroup/RFIDtools/blob/master/app_main/src/main/assets/proxmark3.zip)

**Comment by ca1e** [comment]
> Yes, we can use rrg repo, that is latest.
> If your want to use termux view:
> 
> 1. You must to cross compile pm3 client
> 2. [Update into file](https://github.com/RfidResearchGroup/RFIDtools/blob/master/app_main/src/main/assets/proxmark3.zip)

Hi,thanks for reply. I just cannot find pm3 client in the zip file but the app still show me an old version after install.could you plz share more details?any wechat plz?

**Pull request merged**
